### ISSUE TITLE
Ensure that the RDKit's data directory and supporting files are installed

### ISSUE THREAD

**Issue by greglandrum** [kuelumbus/rdkit-pypi#20] opened 2021-11-11 14:54 UTC
I keep getting pinged by people who are using rdkit-pypi reporting that RDKit scripts or examples don't work. The common thread through these problems is that the PyPi packages of the RDKit don't include the RDKit's Data directory or configure the installation to know where to find that. This breaks some RDKit functionality.

Here's one example of the consequences of that.
Using rdkit-pypi
```
In [2]: from rdkit.Chem import Descriptors

In [3]: len(Descriptors._descList)
Out[3]: 115
```
Using the conda-forge package:
```
In [2]: from rdkit.Chem import Descriptors

In [3]: len(Descriptors._descList)
Out[3]: 208
```
This particular failure is because the file containing fragment definitions (which lives in the data directory) can't be found.

Here's another example: the SaltRemover doesn't work because it can't find the salt list:
```
In [1]: from rdkit.Chem.SaltRemover import SaltRemover

In [2]: rm = SaltRemover()
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-db353f6533c0> in <module>
----> 1 rm = SaltRemover()

~/miniconda3/envs/py38_pypi/lib/python3.8/site-packages/rdkit/Chem/SaltRemover.py in __init__(self, defnFilename, defnData, defnFormat)
     90         self.salts = None
     91         self.defnFormat = defnFormat
---> 92         self._initPatterns()
     93 
     94     def _initPatterns(self):

~/miniconda3/envs/py38_pypi/lib/python3.8/site-packages/rdkit/Chem/SaltRemover.py in _initPatterns(self)
    135         else:
    136             if self.defnFormat == InputFormat.SMARTS:
--> 137                 self.salts = [mol for mol in _getSmartsSaltsFromFile(self.defnFilename)]
    138             elif self.defnFormat == InputFormat.MOL:
    139                 self.salts = [mol for mol in SDMolSupplier(self.defnFilename)]

~/miniconda3/envs/py38_pypi/lib/python3.8/site-packages/rdkit/Chem/SaltRemover.py in _getSmartsSaltsFromFile(filename)
     78     Extracts SMARTS salts from given file object.
     79     """
---> 80     return _getSmartsSaltsFromStream(open(filename, 'r'))
     81 
     82 

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-vnsiyh88/build/temp.linux-x86_64-3.8/rdkit_install/share/RDKit/Data/Salts.txt'
```

The conda packages create a directory in the environment's `share` directory which holds this stuff:
```
In [2]: RDConfig.RDDataDir
Out[2]: '/home/glandrum/miniconda3/envs/py38_rdkit/share/RDKit/Data'
```
But there's no such thing being done for rdkit-pypi.

We had a thread about this at some point, but it looks like nothing has been done to fix the problem. Please do something about this... I think it's great that you are making these packages available, but the packages being provided are broken and are increasing the support burden on me (and, I assume, other RDKit devs).

**Comment by kuelumbus** [comment] 2021-11-11 16:31
Hi Greg,

I am sorry to hear that this is burden for you and other developers; that should obviously not be the case. I was not aware of these issues, otherwise I would have tried to fix it. So, in case you (or other devs) get pinged again on such problems, please feel free to transfer the issue, ask to open an issue in this Github repo, or just link me to the issue so I get notified.

Regarding the problems, I believe they should all be fixed in the current rdkit-pypi version.

```python
$ ipython
Python 3.9.7 (default, Oct 25 2021, 20:08:18) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from rdkit.Chem import Descriptors

In [2]: len(Descriptors._descList)
Out[2]: 208

In [3]: from rdkit.Chem.SaltRemover import SaltRemover

In [4]: rm = SaltRemover()

In [5]: from rdkit import RDConfig

In [6]: RDConfig.RDDataDir
Out[6]: '/home/chris/.local/lib/python3.9/site-packages/rdkit/Data'
```
To resolve this, I propose

1. Update to the newest rdkit-pypi version. Data files were missing in the first couple of version that I have uploaded to PyPi. The newest version should have all the files with the correct paths.
1. If this does not help. This might be a problem in the MacOS wheels. Are you on Mac? (My output is from Linux)

Sorry for the inconvenience,
Chris

**Comment by greglandrum** [comment] 2021-11-11 16:46
Hi Chris.

That's awesome. I don't know when I did the pip install to do the testing, but clearly it was too long ago.
I just reinstalled and things work, as you show above.

Thanks for the quick response and correction. :-)

-greg

**Closed** 2021-11-11 16:46 UTC

**Comment by kuelumbus** [comment] 2021-11-11 16:53
No problem Greg. Glad this got resolved. 🥳

**Comment by greglandrum** [comment] 2021-12-14 14:35
Hi @kuelumbus , I'm afraid that this has either gotten messed up again or I tested it badly last time.
I just installed the new rdkit-pypi on my linux box, made sure I don't have RDBASE set in that shell, and see this:
```
(py38_pypi) glandrum@Badger:~/ETH/Projects/molecular_time_series$ python -c 'import rdkit;print(rdkit.__version__);from rdkit import RDConfig;print(RDConfig.RDDataDir)'
2021.09.3
Data
```

**Comment by kuelumbus** [comment] 2021-12-14 15:09
I can't reproduce this on my ubuntu machine. It seems like everything is set correctly on here.

```bash
for version in 2021.3.5 2021.9.1 2021.9.2 2021.9.3; do ( poetry add -q rdkit-pypi@$version; poetry run python -c "import rdkit;print(rdkit.__version__);from rdkit import RDConfig;print(RDConfig.RDDataDir)" ) done
  • Updating rdkit-pypi (2021.9.3 -> 2021.3.5)
2021.03.5
/data/chris/test_poetry/.venv/lib/python3.8/site-packages/rdkit/Data
  • Updating rdkit-pypi (2021.3.5 -> 2021.9.1)
2021.09.11
/data/chris/test_poetry/.venv/lib/python3.8/site-packages/rdkit/Data
  • Updating rdkit-pypi (2021.9.1 -> 2021.9.2)
2021.09.2
/data/chris/test_poetry/.venv/lib/python3.8/site-packages/rdkit/Data
  • Updating rdkit-pypi (2021.9.2 -> 2021.9.3)
2021.09.3
/data/chris/test_poetry/.venv/lib/python3.8/site-packages/rdkit/Data
```
During building the wheels, I replace `_share` with `_share = os.path.dirname(__file__)` in `RDPaths.py`. Can you past the output of RDConfig in your configurations:
```bash
from rdkit import RDConfig
RDConfig.__file__
'/data/chris/test_poetry/.venv/lib/python3.8/site-packages/rdkit/RDConfig.py'
```

**Comment by greglandrum** [comment] 2021-12-14 15:13
ARGH. User error. Again...
`export RDBASE=""` does not, of course, remove `RDBASE` from the environment.
If I do `unset RDBASE` then things work.

I'm guessing that these are not problems that standard users are going to have...

Sorry. Again...

**Comment by kuelumbus** [comment] 2021-12-14 15:15
No problem. It's good to point out these things in case somebody runs into the same problems.
